templates:
    apikeyform: assets/apikeyform.twig
    thankspage: assets/thankspage.twig
form:
    fields:
        email:
            label: Email address
            placeholder: Enter your email address
            type: email
            required: true
        firstName:
            label: First Name
            placeholder: Enter your first name
            type: text
            required: true
        lastName:
            label: Last Name
            placeholder: Enter your last name
            type: text
            required: true
        company:
            label: Organisation
            placeholder: Please enter the organization name in English
            type: text
            required: false
    submit:
        label: Request key
credentials:
    base_uri: http://www.europeana.eu/api/
    login_url: http://www.europeana.eu/api/login.do
    destination: http://www.europeana.eu/api/apikey
    fields:
        j_username: 'override in deploy scripts'
        j_password: 'override in deploy scripts'
recaptcha:
    enabled: false
    remoteurl: 'https://www.google.com/recaptcha/api/siteverify'
    sitekey: 'override in deploy scripts'
    secret: 'override in deploy scripts'
