## For information on how to use thie file, see the documentation at the repo home:
## github.com/foundrycode/boltredirector

# Options - Set Options for the Extension

options:

    # Auto slugging should be enabled. Makes slugs friendly. Like cats.

    autoSlug: true

    # If there is a query string, append it to the destination path.
    # Disabled by default as Bolt generally doesn't need them. But, if
    # you have an extension that does need them, best to turn it on.

    appendQueryString: false

# Redirects - The Main Redirects for this Installation

redirects:
    '/api/linked-open-data/Credits': '/api/linked-open-data-credits'
    '/api/linked-open-data/data-downloads': '/api/linked-open-data-data-downloads'
    '/api/linked-open-data/data-structure': '/api/linked-open-data-data-structure'
    '/api/linked-open-data/FAQ': '/api/linked-open-data-faq'
    '/api/linked-open-data/introduction': '/api/linked-open-data-introduction'
    '/api/linked-open-data/SPARQL-endpoint': '/api/linked-open-data-sparql-endpoint'
    '/api/oai-pmh/access-key': '/api/oai-pmh-access-key'
    '/api/oai-pmh/credits': '/api/oai-pmh-credits'
    '/api/oai-pmh/getting-started': '/api/oai-pmh-getting-started'
    '/api/oai-pmh/introduction': '/api/oai-pmh-introduction'
    '/api/oai-pmh/resources': '/api/oai-pmh-resources'

variables:



# JIT (Just In Time) Replacements
#
# These replacements are made just before the actual redirect, so they
# must match any parts in `to` patterns from the above array.
#
# For conciseness, try to match an entire destination, as other URIs
# could be inadvertantly affected. If other URIs won't contain the
# string, then you can keep it as short as needed.
#
# Also, regular expressions are allowed here. Capture with \\n.

jits:
  '/foo': '/bar'
