# possibles child contenttypes
contenttypes: [ pages, blogs, publications, events, persons, structures ]
# parent structure handle child contenttypes
parenttype: structures
# sitemap settings
# 
# source options to specify the content
# every source is listed in a seperate list. except 'menu' option
# three 'types':
#   - type:     'menu' get menu by name and seach childs recursively
#   - type:     'list' 
#     - link:     simple link with label + link
#       - label
#       - link
#     - link:     slug link with label + slug
#       - label
#       - slug
# 
# todo: cleanup
#
sitemap:
  sources:
    source_1:
      type: 'menu'
      data:
        menu: 'primary'
    source_2:
      type: 'list'
      label: 'More info'
      data:
        blog:
          label: 'Blog'
          link: '/blog'
        events:
          label: 'Events'
          link: '/events'
        about:
          label: 'About Us'
          slug: 'about-us'
  contenttypes: ['persons', 'structures', 'pages', 'blogs', 'events' ]
  template: 'sitemap.twig'
  xml_template: 'sitemap_xml.twig'
