primary:
  - label: 'Home'
    title: 'Europeana Labs home'
    path: /
  - label: 'APIs'
    title: 'Documentation for the Europeana API'
    path: /api
  - label: 'Apps'
    path: /apps
    title: 'Apps showcase'
  - label: 'Data'
    path: /data
    title: 'Open datasets for re-use'
  - label: 'Blog'
    path: /blog
    title: 'Europeana Labs blog'
  - label: 'Events'
    path: /events
    title: 'Europeana Labs blog'
  - label: 'Incubation'
    path: /incubation
    title: 'Business incubation from Europeana'
  - label: 'Support'
    path: /support
    title: 'Support for users of the API and Europeana Labs'

footer:
  - title: Home
    path: homepage
    label: Home
  - title: 'Terms & policies'
    link: http://europeana.eu/portal/rights/terms-and-policies.html
    label: 'Terms & policies'
  - title: Sitemap
    path: /sitemap
    label: Sitemap
  - label: 'About us'
    path: /about-us
    title: 'About Europeana Research'

Explorer-Europeana:
  - title: Search portal
    path: /sitemap
    label: Search portal
  - title: Labs
    path: /sitemap
    label: Labs
  - title: 1914-1918
    path: /sitemap
    label: 1914-1918
  - title: End user blog
    path: /sitemap
    label: End user blog
