main:
    slug: main
    singular_slug: main
    behaves_like: grouping
    options: [toplevel1, toplevel2, toplevel3, toplevel4]
    has_sortorder: false

appthemes:
  slug: appthemes
  name: Type
  singular_slug: type
  singular_name: Type
  behaves_like: categories
  options: [Showcase, Tools, FLOSS]

appcategories:
  name: Theme
  slug: appcategories
  singular_name: Theme
  singular_slug: theme
  behaves_like: categories
  multiple: 1
  options: [API Implementation, Discovery, Hackathon Prototype, R&D Results, Curation/Annotation,Education, Client Library, Pilot, Gaming, Distribution, Tourism, Linked Open Data]
  
apptags:
  slug: apptags
  name: Tags
  singular_name: Tag
  behaves_like: tags

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    listing_template: tag_listing.twig
    
tree:
    slug: tree
    singular_slug: tree
    behaves_like: grouping
    options:
        pages: 'Pages'
        collections: 'Our collections'
        about-our-data: 'About our data'
        work-with-us: 'Work with us'
        about-us: 'About us'
        staff: 'Staff'
    multiple: false
    has_sortorder: true

